CREATE TABLE `pos_order` (
  `orderId` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `orderNo` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `account` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `customerName` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `operatorName` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `originPrice` double(10,2) DEFAULT NULL,
  `changePrice` double(10,2) DEFAULT NULL,
  `totalNum` int DEFAULT NULL,
  `getNum` int DEFAULT NULL,
  `returnNum` int DEFAULT NULL,
  `getPrice` double(10,2) DEFAULT NULL,
  `returnPrice` double(10,2) DEFAULT NULL,
  `ctime` datetime DEFAULT NULL,
  `ymd` date DEFAULT NULL,
  UNIQUE KEY `unq_account` (`orderId`,`orderNo`,`account`) USING BTREE,
  KEY `account` (`account`),
  KEY `ymd` (`ymd`),
  KEY `idx_orderno` (`orderNo`),
  KEY `idx_orderid` (`orderId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;